use Customer_behavior
--select*from [customer_shopping_behavior (1)]
--Q1. What is the total revenue generated by male vs. female customers?
select gender,sum(purchase_amount) as revenue
from [customer_shopping_behavior (1)]
group by gender

--Q2. Which customers used a discount but still spent more than the average purchase amount? 
select customer_id,purchase_amount
from [customer_shopping_behavior (1)]
where discount_applied='yes' and purchase_amount>= (select avg(purchase_amount) from [customer_shopping_behavior (1)])

-- Q3. Which are the top 5 products with the highest average review rating?
select top 5 item_purchased,avg(review_rating) as avg_review_rating
from [customer_shopping_behavior (1)]
group by item_purchased
order by avg_review_rating desc
-- we can round average rating
select top 5 item_purchased,round(avg(review_rating),2) as avg_review_rating
from [customer_shopping_behavior (1)]
group by item_purchased
order by avg_review_rating desc

--Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
select shipping_type, avg(purchase_amount)
from [customer_shopping_behavior (1)]
where shipping_type in ('Standard','Express')
group by shipping_type

--Q5. Do subscribed customers spend more? Compare average spend and total revenue 
--between subscribers and non-subscribers.
select subscription_status,
count(customer_id)as total_customer,
avg(purchase_amount)as average_spend,
sum(purchase_amount)as total_revenue
from [customer_shopping_behavior (1)]
group by subscription_status
order by average_spend,total_revenue desc

--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
select top 5 item_purchased as products,
Round(100.0 * sum(case when discount_applied = 'yes' then 1 else 0 end)/count(*),2) as discount_rate
from [customer_shopping_behavior (1)]
group by item_purchased
order by discount_rate desc

--Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 

with  customer_type as (
select customer_id,previous_purchases,
CASE
    when previous_purchases = 1 then 'New'
	when previous_purchases between 2 and 10 then 'returning'
	else 'loyal'
	end as customer_segment
from [customer_shopping_behavior (1)])
select customer_segment,count(*) as 'number_of_customer'
from customer_type
group by customer_segment

--Q8. What are the top 3 most purchased products within each category? 

with item_counts as(
    select category,
           item_purchased,
	       count(customer_id)as total_orders,
	       Row_number() over(
	       partition by category
	       order by count(customer_id)
	       ) as item_rank
    from [customer_shopping_behavior (1)]
	group by category,item_purchased
 )
    select item_rank,category,item_purchased,total_orders 
    from item_counts
    where item_rank <=3

--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status,
       COUNT(customer_id) AS repeat_buyers
FROM [customer_shopping_behavior (1)]
WHERE previous_purchases > 5
GROUP BY subscription_status

--Q10. What is the revenue contribution of each age group? 
select age_group , Sum(purchase_amount) as revenue
from [customer_shopping_behavior (1)]
group by age_group
order by revenue desc

SELECT @@SERVERNAME AS ServerName